export const mockMembers: Member[] = [
  {
    id: '1',
    name: 'Pastor John Emmanuel',
    roles: ['Leader-in-charge'],
    band: ['Love Divine', 'Choir'],
    rank: 1,
    phone: '+234 801 234 5678',
    email: 'pastor.john@church.com',
    address: 'Lagos, Nigeria',
    joinDate: '2010-01-15',
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    department: 'Leadership',
    active: true,
    bio: 'Dedicated servant of God with over 15 years of pastoral experience.',
  },
  {
    id: '2',
    name: 'Elder Mary Adebayo',
    roles: ['Captain Mary Band'],
    band: ['Choir', 'Deborah'],
    rank: 2,
    phone: '+234 802 345 6789',
    email: 'elder.mary@church.com',
    address: 'Ikeja, Lagos',
    joinDate: '2012-03-20',
    image:
      'https://images.unsplash.com/photo-1494790108755-2616c96ce29f?w=150&h=150&fit=crop&crop=face',
    department: 'Women Ministry',
    active: true,
    bio: 'Passionate about women empowerment and spiritual counseling.',
  },
  {
    id: '3',
    name: 'Deacon Paul Okafor',
    roles: ['Youth President', 'Assistant Choir Coordinator'],
    band: [],
    rank: 3,
    phone: '+234 803 456 7890',
    email: 'deacon.paul@church.com',
    address: 'Victoria Island, Lagos',
    joinDate: '2013-07-10',
    image:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    department: 'Deacon Board',
    bio: 'Committed to serving the church through administrative excellence.',
    active: true
  },
  {
    id: '4',
    name: 'Sister Grace Nkem',
    roles: ['Choir Director', 'Vice Captain John Beloved Band'],
    band: [],
    rank: 4,
    phone: '+234 804 567 8901',
    email: 'grace.nkem@church.com',
    address: 'Surulere, Lagos',
    joinDate: '2015-02-28',
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    department: 'Music Ministry',
    active: false,
    bio: 'Leading the congregation in heartfelt worship through music.',
  },
  {
    id: '5',
    name: 'Brother David Chukwu',
    roles: ['Youth Pastor'],
    band: [],
    rank: 5,
    phone: '+234 805 678 9012',
    email: 'david.youth@church.com',
    address: 'Lekki, Lagos',
    joinDate: '2016-09-15',
    image:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    department: 'Youth Ministry',
    active: false,
    bio: 'Empowering young people to fulfill their God-given potential.',
  },
  {
    id: '6',
    name: 'Sister Ruth Akin',
    roles: ['Children Coordinator'],
    band: [],
    rank: 6,
    phone: '+234 806 789 0123',
    email: 'ruth.children@church.com',
    address: 'Gbagada, Lagos',
    joinDate: '2017-05-12',
    image:
      'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop&crop=face',
    department: 'Children Ministry',
    active: true,
    bio: 'Nurturing the next generation with love and biblical teachings.',
  },
  {
    id: '7',
    name: 'Brother Samuel Eze',
    roles: ['Usher Coordinator'],
    band: [],
    rank: 7,
    phone: '+234 807 890 1234',
    email: 'samuel.usher@church.com',
    address: 'Ikorodu, Lagos',
    joinDate: '2018-01-20',
    image:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    department: 'Protocol',
    active: true,
    bio: 'Ensuring every visitor feels welcomed and comfortable.',
  },
  {
    id: '8',
    name: 'Sister Faith Okoro',
    roles: ['Secretary'],
    band: [],
    rank: 8,
    phone: '+234 808 901 2345',
    email: 'faith.secretary@church.com',
    address: 'Ajah, Lagos',
    joinDate: '2019-08-14',
    image:
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
    department: 'Administration',
    active: true,
    bio: 'Maintaining accurate records and supporting church operations.',
  },
];
