import { Bands } from '@/src/enum/bands';

export enum ContactType {
  Email = 'email',
  Phone = 'phone',
}

export const mockMembers: MemberProfile[] = [
  {
    id: '1',
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    firstName: 'John',
    lastName: 'Emmanuel',
    email: 'john.emmanuel@church.com',
    title: 'Prophet',
    phone: ['+234 801 234 5678', '+234 703 456 7890'],
    band: [Bands.Choir, Bands.Deborah],
    // role: Role.Prophet,
    position: ['Leader-in-charge', 'Senior Pastor'],
    rank: 1,
    address: '12 Victoria Island, Lagos, Nigeria',
    joinDate: '2010-01-15',
    status: 'active',
    verified: true,
    gender: 'Male',
    dob: '1975-09-20',
    memberSince: '2010-01-15',
    department: 'Pastoral',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Email,
    secondaryContact: '+234 801 234 5678',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '2',
    avatar:
      'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
    firstName: 'Mary',
    lastName: 'Johnson',
    email: 'mary.johnson@church.com',
    title: 'Sister',
    phone: ['+234 802 345 6789'],
    band: [Bands.QueenEsther, Bands.GoodWomen],
    // role: Role.Elder,
    position: ['Women Leader', 'Choir Coordinator'],
    rank: 2,
    address: '45 Allen Avenue, Ikeja, Lagos, Nigeria',
    joinDate: '2012-03-22',
    status: 'active',
    verified: true,
    gender: 'Female',
    dob: '1982-11-15',
    memberSince: '2012-03-22',
    department: 'Women Ministry',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Phone,
    secondaryContact: 'mary.johnson@church.com',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '3',
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    firstName: 'David',
    lastName: 'Adebayo',
    email: 'david.adebayo@gmail.com',
    title: 'Brother',
    phone: ['+234 803 456 7890'],
    band: [Bands.Daniel, Bands.JohnBeloved],
    // role: Role.Deacon,
    position: ['Youth Coordinator', 'Sound Engineer'],
    rank: 15,
    address: '78 Surulere Street, Lagos, Nigeria',
    joinDate: '2015-07-10',
    status: 'active',
    verified: false,
    gender: 'Male',
    dob: '1990-05-08',
    memberSince: '2015-07-10',
    department: 'Youth Ministry',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Email,
    emailVerified: false,
    phoneVerified: true,
  },
  {
    id: '4',
    avatar:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    firstName: 'Grace',
    lastName: 'Okonkwo',
    email: 'grace.okonkwo@yahoo.com',
    title: 'Sister',
    phone: ['+234 804 567 8901', '+234 706 789 0123'],
    band: [Bands.Choir, Bands.HolyMary],
    // role: Role.Minister,
    position: ['Worship Leader', 'Prayer Coordinator'],
    rank: 8,
    address: '23 Ikoyi Crescent, Lagos, Nigeria',
    joinDate: '2018-02-14',
    status: 'active',
    verified: true,
    gender: 'Female',
    dob: '1988-12-03',
    memberSince: '2018-02-14',
    department: 'Worship',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Email,
    secondaryContact: '+234 804 567 8901',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '5',
    avatar:
      'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop&crop=face',
    firstName: 'Samuel',
    lastName: 'Okafor',
    email: 'samuel.okafor@hotmail.com',
    title: 'Brother',
    phone: ['+234 805 678 9012'],
    band: [Bands.YouthFellowship, Bands.Faith],
    // role: Role.Member,
    position: ['Youth Member'],
    rank: 25,
    address: '67 Maryland Estate, Lagos, Nigeria',
    joinDate: '2020-11-30',
    status: 'active',
    verified: false,
    gender: 'Male',
    dob: '1995-07-22',
    memberSince: '2020-11-30',
    department: 'Youth',
    hasPassword: false,
    accountType: 'guest',
    primaryContact: ContactType.Phone,
    emailVerified: false,
    phoneVerified: false,
  },
  {
    id: '6',
    avatar:
      'https://images.unsplash.com/photo-1554151228-14d9def656e4?w=150&h=150&fit=crop&crop=face',
    firstName: 'Esther',
    lastName: 'Akinwale',
    email: 'esther.akinwale@church.com',
    title: 'Deaconess',
    phone: ['+234 806 789 0123'],
    band: [Bands.Deborah, Bands.QueenEsther, Bands.GoodWomen],
    // role: Role.Leader,
    position: ['Women Ministry Leader', 'Counselor'],
    rank: 5,
    address: '89 Lekki Phase 1, Lagos, Nigeria',
    joinDate: '2013-09-05',
    status: 'active',
    verified: true,
    gender: 'Female',
    dob: '1978-04-18',
    memberSince: '2013-09-05',
    department: 'Counseling',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Email,
    secondaryContact: '+234 806 789 0123',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '7',
    avatar:
      'https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=150&h=150&fit=crop&crop=face',
    firstName: 'Peter',
    lastName: 'Nwankwo',
    email: 'peter.nwankwo@gmail.com',
    title: 'Elder',
    phone: ['+234 807 890 1234', '+234 708 901 2345'],
    band: [Bands.Warden, Bands.JohnBeloved],
    // role: Role.Elder,
    position: ['Church Warden', 'Finance Committee'],
    rank: 3,
    address: '34 Gbagada Estate, Lagos, Nigeria',
    joinDate: '2011-06-12',
    status: 'active',
    verified: true,
    gender: 'Male',
    dob: '1970-10-25',
    memberSince: '2011-06-12',
    department: 'Administration',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Phone,
    secondaryContact: 'peter.nwankwo@gmail.com',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '8',
    avatar:
      'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&h=150&fit=crop&crop=face',
    firstName: 'Rebecca',
    lastName: 'Ojo',
    email: 'rebecca.ojo@outlook.com',
    title: 'Sister',
    phone: ['+234 808 901 2345'],
    band: [Bands.ChildrenMinistry, Bands.HolyMary],
    // role: Role.Minister,
    position: ['Children Ministry Leader', 'Sunday School Teacher'],
    rank: 12,
    address: '56 Ajah Road, Lagos, Nigeria',
    joinDate: '2016-12-08',
    status: 'active',
    verified: true,
    gender: 'Female',
    dob: '1985-08-14',
    memberSince: '2016-12-08',
    department: 'Children Ministry',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Email,
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '9',
    avatar:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop&crop=face',
    firstName: 'Joshua',
    lastName: 'Bamidele',
    email: 'joshua.bamidele@church.com',
    title: 'Pastor',
    phone: ['+234 809 012 3456'],
    band: [Bands.LoveDevine, Bands.Faith],
    // role: Role.Pastor,
    position: ['Assistant Pastor', 'Evangelism Leader'],
    rank: 4,
    address: '91 Festac Town, Lagos, Nigeria',
    joinDate: '2014-04-20',
    status: 'active',
    verified: true,
    gender: 'Male',
    dob: '1980-01-30',
    memberSince: '2014-04-20',
    department: 'Evangelism',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Email,
    secondaryContact: '+234 809 012 3456',
    emailVerified: true,
    phoneVerified: true,
  },
  {
    id: '10',
    avatar:
      'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=150&h=150&fit=crop&crop=face',
    firstName: 'Ruth',
    lastName: 'Okoro',
    email: 'ruth.okoro@gmail.com',
    title: 'Sister',
    phone: ['+234 810 123 4567'],
    band: [Bands.Choir, Bands.YouthFellowship],
    // role: Role.Member,
    position: ['Choir Member', 'Usher'],
    rank: 30,
    address: '15 Mushin Road, Lagos, Nigeria',
    joinDate: '2022-08-15',
    status: 'inactive',
    verified: false,
    gender: 'Female',
    dob: '1992-06-12',
    memberSince: '2022-08-15',
    department: 'Music',
    hasPassword: true,
    accountType: 'member',
    primaryContact: ContactType.Phone,
    secondaryContact: 'ruth.okoro@gmail.com',
    emailVerified: false,
    phoneVerified: true,
  },
];
