import { Bands } from '@/src/enum/bands';

export const mockMembers: Member[] = [
  {
    id: '1',
    title: 'Prophet',
    firstName: 'John',
    lastName: 'Emmanuel',
    roles: ['Leader-in-charge'],
    band: [Bands.Choir, Bands.Deborah, Bands.QueenEsther],
    rank: 1,
    phone: ['+234 801 234 5678'],
    email: 'pastor.john@church.com',
    address: 'Lagos, Nigeria',
    joinDate: '2010-01-15',
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Male',
    dob: 'Sept 20',
  },
  {
    id: '2',
    title: 'Sister',
    firstName: 'Mary',
    lastName: 'Adebayo',
    roles: ['Captain Mary Band'],
    band: [Bands.LoveDevine, Bands.Deborah],
    rank: 2,
    phone: ['+234 802 345 6789'],
    email: 'elder.mary@church.com',
    address: 'Ikeja, Lagos',
    joinDate: '2012-03-20',
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Female',
    dob: 'Sept 20',
  },
  {
    id: '3',
    title: 'Brother',
    firstName: 'Okafor',
    lastName: 'Paul',
    roles: ['Youth President', 'Assistant Choir Coordinator'],
    band: [Bands.YouthFellowship],
    rank: 3,
    phone: ['+234 803 456 7890'],
    email: 'deacon.paul@church.com',
    address: 'Victoria Island, Lagos',
    joinDate: '2013-07-10',
    image:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Male',
    dob: 'Sept 20',
  },
  {
    id: '4',
    title: 'Prophet',
    firstName: 'John',
    lastName: 'Emmanuel',
    roles: ['Leader-in-charge'],
    band: [Bands.Warden],
    rank: 4,
    phone: ['+234 801 234 5678'],
    email: 'pastor.john@church.com',
    address: 'Lagos, Nigeria',
    joinDate: '2010-01-15',
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Male',
    dob: 'Sept 20',
  },
  {
    id: '5',
    title: 'Sister',
    firstName: 'Mary',
    lastName: 'Adebayo',
    roles: ['Captain Mary Band'],
    band: [Bands.GoodWomen, Bands.Deborah],
    rank: 5,
    phone: ['+234 802 345 6789'],
    email: 'elder.mary@church.com',
    address: 'Ikeja, Lagos',
    joinDate: '2012-03-20',
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Female',
    dob: 'Sept 20',
  },
  {
    id: '6',
    title: 'Brother',
    firstName: 'Okafor',
    lastName: 'Paul',
    roles: [Bands.Daniel, Bands.Deborah],
    band: [],
    rank: 6,
    phone: ['+234 803 456 7890'],
    email: 'deacon.paul@church.com',
    address: 'Victoria Island, Lagos',
    joinDate: '2013-07-10',
    image:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Male',
    dob: 'Sept 20',
  },
  {
    id: '7',
    title: 'Prophet',
    firstName: 'John',
    lastName: 'Emmanuel',
    roles: ['Leader-in-charge'],
    band: [Bands.Warden],
    rank: 4,
    phone: ['+234 801 234 5678'],
    email: 'pastor.john@church.com',
    address: 'Lagos, Nigeria',
    joinDate: '2010-01-15',
    image:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Male',
    dob: 'Sept 20',
  },
  {
    id: '8',
    title: 'Sister',
    firstName: 'Mary',
    lastName: 'Adebayo',
    roles: ['Captain Mary Band'],
    band: [Bands.GoodWomen, Bands.Deborah],
    rank: 5,
    phone: ['+234 802 345 6789'],
    email: 'elder.mary@church.com',
    address: 'Ikeja, Lagos',
    joinDate: '2012-03-20',
    image:
      'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Female',
    dob: 'Sept 20',
  },
  {
    id: '9',
    title: 'Brother',
    firstName: 'Okafor',
    lastName: 'Paul',
    roles: [Bands.Daniel, Bands.Deborah],
    band: [],
    rank: 6,
    phone: ['+234 803 456 7890'],
    email: 'deacon.paul@church.com',
    address: 'Victoria Island, Lagos',
    joinDate: '2013-07-10',
    image:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    status: 'Active',
    verified: true,
    gender: 'Male',
    dob: 'Sept 20',
  },
];
