export enum ContactType {
  Email = 'email',
  Phone = 'phone',
}

export const mockMembers: MemberProfile[] = [
  {
    memberId: '11',
    uid: '11 asdcaswd',
    avatar:
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    firstName: 'Emmanuel',
    lastName: 'Adeyemi',
    email: 'emmanuel.adeyemi@gmail.com',
    title: 'Deacon',
    band: ['Choir', 'Usher'],
    position: ['Leader', 'Assistant'],
    address: '21 Example Street, City',
    joinDate: '2021-01-12',
    createdAt: new Date().toISOString(),
    status: 'active',
    verified: false,
    gender: 'male',
    dob: '1991-12-15',
    memberSince: '2021-01-01',
    department: ['ICT'],
    hasPassword: false,
    accountType: 'member',
    authType: ContactType.Email,
    primaryPhone: '+234801234567890',
    secondaryPhone: '+234809876543210',
    emailVerified: false,
    phoneVerified: true,
  },
  {
    memberId: '12',
    uid: '12 asdcaswd',
    avatar:
      'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&h=150&fit=crop&crop=face',
    firstName: 'Blessing',
    lastName: 'Ogbonna',
    email: 'blessing.ogbonna@church.com',
    title: 'Prophetess',
    band: ['Choir', 'Usher', 'Drama'],
    position: ['Leader'],
    address: '22 Example Street, City',
    joinDate: '2022-01-13',
    createdAt: new Date().toISOString(),
    status: 'inactive',
    verified: true,
    gender: 'female',
    dob: '1992-13-15',
    memberSince: '2022-01-01',
    department: ['Secteriat'],
    hasPassword: true,
    accountType: 'member',
    authType: ContactType.Phone,
    primaryPhone: '+234801234567891',
    emailVerified: true,
    phoneVerified: false,
  },
  {
    memberId: '13',
    uid: '13 asdcaswd',
    avatar:
      'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
    firstName: 'Daniel',
    lastName: 'Uzoma',
    email: 'daniel.uzoma@yahoo.com',
    title: 'Brother',
    band: ['Choir'],
    position: ['Leader', 'Assistant', 'Member'],
    address: '23 Example Street, City',
    joinDate: '2023-01-14',
    createdAt: new Date().toISOString(),
    status: 'active',
    verified: false,
    gender: 'male',
    dob: '1993-14-15',
    memberSince: '2023-01-01',
    department: ['Media'],
    hasPassword: false,
    accountType: 'member',
    authType: ContactType.Email,
    primaryPhone: '+234801234567892',
    secondaryPhone: '+234809876543212',
    emailVerified: false,
    phoneVerified: true,
  },
  {
    memberId: '14',
    uid: '14 asdcaswd',
    avatar:
      'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=150&h=150&fit=crop&crop=face',
    firstName: 'Mercy',
    lastName: 'Ikechukwu',
    email: 'mercy.ikechukwu@hotmail.com',
    title: 'Sister',
    band: ['Choir', 'Drama', 'Prayer'],
    position: ['Leader', 'Assistant'],
    address: '24 Example Street, City',
    joinDate: '2024-01-15',
    createdAt: new Date().toISOString(),
    status: 'inactive',
    verified: true,
    gender: 'female',
    dob: '1994-15-15',
    memberSince: '2024-01-01',
    department: ['Drama'],
    hasPassword: true,
    accountType: 'member',
    authType: ContactType.Phone,
    primaryPhone: '+234801234567893',
    emailVerified: true,
    phoneVerified: false,
  },
  {
    memberId: '15',
    uid: '15 asdcaswd',
    avatar:
      'https://images.unsplash.com/photo-1463453091185-61582044d556?w=150&h=150&fit=crop&crop=face',
    firstName: 'Joseph',
    lastName: 'Olumide',
    email: 'joseph.olumide@church.com',
    title: 'Apostle',
    band: ['Choir', 'Usher', 'Prayer', 'Media'],
    position: ['Leader'],
    address: '25 Example Street, City',
    joinDate: '2025-01-16',
    createdAt: new Date().toISOString(),
    status: 'active',
    verified: false,
    gender: 'male',
    dob: '1995-16-15',
    memberSince: '2025-01-01',
    department: ['Treasury'],
    hasPassword: false,
    accountType: 'admin',
    authType: ContactType.Email,
    primaryPhone: '+234801234567894',
    secondaryPhone: '+234809876543214',
    emailVerified: false,
    phoneVerified: true,
  },
];
