export const DEPARTMENTS_CONFIG = [
  {
    id: 'interpretation',
    name: 'Interpretation',
    description:
      'Translating and interpreting services for multilingual congregation',
    memberCount: 18,
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#3B82F6', '#1E40AF'],
    icon: 'bubble.left.and.bubble.right.fill',
    meetingDay: 'Thursdays 6:00 PM',
  },
  {
    id: 'programme',
    name: 'Programme',
    description:
      'Planning, organizing and coordinating all church events and services',
    memberCount: 25,
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#10B981', '#047857'],
    icon: 'calendar.badge.plus',
    meetingDay: 'Tuesdays 7:00 PM',
  },
  {
    id: 'media',
    name: 'Media',
    description:
      'Managing church communications, photography, and video production',
    memberCount: 22,
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#8B5CF6', '#7C3AED'],
    icon: 'camera.fill',
    meetingDay: 'Wednesdays 6:30 PM',
  },
  {
    id: 'treasury',
    name: 'Treasury',
    description:
      'Managing church finances, tithes, offerings and financial records',
    memberCount: 12,
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#F59E0B', '#D97706'],
    icon: 'dollarsign.circle.fill',
    meetingDay: 'Fridays 7:30 PM',
  },
  {
    id: 'technical',
    name: 'Technical',
    description:
      'Sound engineering, lighting, and audiovisual equipment management',
    memberCount: 20,
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#06B6D4', '#0891B2'],
    icon: 'speaker.wave.3.fill',
    meetingDay: 'Saturdays 5:00 PM',
  },
  {
    id: 'drama',
    name: 'Drama',
    description:
      'Theatrical performances, skits, and creative presentations for ministry',
    memberCount: 30,
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#EC4899', '#BE185D'],
    icon: 'theatermasks.fill',
    meetingDay: 'Saturdays 3:00 PM',
  },
  {
    id: 'it',
    name: 'IT',
    description:
      'Information Technology, website management, and digital infrastructure',
    memberCount: 15,
    ageRange: '18+ years',
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#6366F1', '#4338CA'],
    icon: 'desktopcomputer',
    meetingDay: 'Thursdays 7:00 PM',
  },
  {
    id: 'evangelism',
    name: 'Evangelism',
    description: 'Spreading the Gospel, soul winning, and outreach programs',
    memberCount: 45,
    ageRange: '16+ years',
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#EF4444', '#DC2626'],
    icon: 'megaphone.fill',
    meetingDay: 'Saturdays 4:00 PM',
  },
  {
    id: 'sanitation',
    name: 'Sanitation',
    description:
      'Maintaining cleanliness and hygiene throughout church premises',
    memberCount: 35,
    ageRange: '16+ years',
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#10B981', '#059669'],
    icon: 'sparkles',
    meetingDay: 'Saturdays 8:00 AM',
  },
  {
    id: 'secretariat',
    name: 'Secretariat',
    description:
      'Handles administrative, documentation, and correspondence tasks for the church',
    memberCount: 3,
    ageRange: '40+ years',
    head: '',
    assistant: '',
    secretary: '',
    gradient: ['#3B82F6', '#2563EB'],
    icon: 'sparkles',
    meetingDay: 'Saturdays 8:00 AM',
  },
];
